



export enum SearchGitHubUsersType {

    ON_CHANGE_SEARCH_INPUT = 'ON_CHANGE_SEARCH_INPUT',
    ON_CLEAR_SEARCH_INPUT = 'ON_CLEAR_SEARCH_INPUT',
    ON_FETCH_GIT_HUB_USERS = 'ON_FETCH_GIT_HUB_USERS',
    ON_FETCH_SUCCESS_GIT_HUB_USERS = 'ON_FETCH_SUCCESS_GIT_HUB_USERS',
    ON_FETCH_ERROR_GIT_HUB_USERS = 'ON_FETCH_ERROR_GIT_HUB_USERS'


}